[update to 0.99.0] Move iaqualink update from climate to component (#26505)
5mauggy (1):
      Fix deConz thermostat integration (#26267)

Aaron Bach (2):
      Fix possible KeyError in SimpliSafe (#26190)
      Bump aiowwlln to 2.0.1 (#26486)

Aleix Murtra (1):
      Add BeeWi SmartClim BLE sensors (#26174)

Alexander (1):
      Add support Slide cover (#25913)

Alexei Chetroi (1):
      Bump ZHA dependencies. (#26504)

Anders Melchiorsen (1):
      Fix race during initial Sonos group construction (#26371)

Andrew Sayre (4):
      Update pyheos to 0.6.0 (#26191)
      Fix flaky updater tests (#26221)
      Cleanup strings (#26243)
      Clean up HEOS strings (#26242)

Balazs Sandor (1):
      Fix onvif camera setup error (#24585)

Bram Kragten (10):
      Speed up history `get_states` (#23881)
      Updated frontend to 20190904.0 (#26421)
      Updated frontend to 20190908.0 (#26524)
      Updated frontend to 20190911.0 (#26578)
      Updated frontend to 20190917.0 (#26686)
      Updated frontend to 20190917.1 (#26691)
      Bump version to 0.99.0b3
      Updated frontend to 20190917.2 (#26696)
      Updated frontend to 20190918.0 (#26704)
      Bump version to 0.99.0b4

Chao (1):
      fix issue setting scan_interval (#26165)

ChristianKuehnel (1):
      added missing bluepy dependency for miflora (#26297)

Costas (1):
      Update google_maps dependency and improve error message (#26361)

Daniel Høyer Iversen (4):
      Update ambiclimate library (#26182)
      Refactor open garage (#26179)
      Upgrade tibber library (#26332)
      Met, check for existing location (#26400)

Daniel Shokouhi (1):
      Add Obihai integration (#26537)

David Bonnes (7):
      Change evohome to asyncio client (#26042)
      Use literal string interpolation in honeywell (#26386)
      Initial commit (#26385)
      Initial commit (#26383)
      bump geniushub client (#26476)
      Bump geniushubclient (#26519)
      Bump geniushub-client to 0.6.13 (#26554)

David F. Mulcahey (8):
      bump quirks version (#26198)
      Add web socket API command to get a single ZHA device (#26196)
      Fix ZHA state restore by always restoring last seen on devices (#26271)
      fix cluster configuration (#26494)
      use newly added is_server for cluster reporting (#26533)
      fix events for smartthings acceleration cluster (#26557)
      osram cluster (#26555)
      bump dependencies (#26576)

Diogo Gomes (1):
      Add precision argument to the Range Filter (#25874)

Eliseo Martelli (1):
      Update sensor.py (#26209)

Erik Montnemery (8):
      Add improvements of device_automation from frontend PR 3514 (#26295)
      Add device automation condition (#26313)
      Add device automation action (#26455)
      Device automations: Rename name to entity_name in translations (#26491)
      Add device automation support to switch entities (#26466)
      Remove device from device action schema (#26536)
      Rename MockToggleDevice to MockToggleEntity (#26644)
      Fix translation, adjust trigger names (#26635)

Fabian Affolter (1):
      Upgrade pyhaversion to 3.1.0 (#26232)

Florent Thoumie (6):
      Add new integration for Jandy iAqualink pool control (#26034)
      Move iaqualink update from climate to component (#26505)
      Add light platform to iaqualink integration (#26484)
      Remove unnecessary force_refresh=True, clarify system behavior (#26543)
      Add sensor platform to iaqualink component (#26544)
      Add switch platform to iaqualink integration (#26545)

Florian Klien (1):
      luci device-tracker dependency fix (#26215)

Franck Nijhof (16):
      Use literal string interpolation in core (f-strings) (#26166)
      Correct file permissions, removing executable bits (#26376)
      Use literal string interpolation in integrations A (f-strings) (#26377)
      Use literal string interpolation in integrations B-D (f-strings) (#26378)
      Use literal string interpolation in integrations E-G (f-strings) (#26379)
      Use literal string interpolation in integrations H-J (f-strings) (#26380)
      Removes executable but from hassfest codeowners (#26381)
      Use literal string interpolation in integrations N-Q (f-strings) (#26391)
      Use literal string interpolation in integrations T-W (f-strings) (#26394)
      Use literal string interpolation in integrations K-M (f-strings) (#26389)
      Use literal string interpolation in integrations R-S (f-strings) (#26392)
      Use literal string interpolation in integrations X-Z (f-strings) (#26395)
      Fixes invalid JSON files and whitespace corrections in YAML files (#26396)
      Migrate legacy typehints in core to PEP-526 (#26403)
      Correct file permissions in slide integration (#26390)
      Replaces IOError by OSError (#26428)

Gerard (1):
      Fix CCM messages (#26589)

Greg Laabs (1):
      Bump ISY994's PyISY dependency to 1.1.2 (#26413)

Hans Oischinger (3):
      Add Viessmann ViCare Climate platform (#26151)
      Vicare: Avoid invalid temperature values (#26485)
      Add more attributes to vicare climate entity (#26521)

HomeAssistant Azure (8):
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update
      [ci skip] Translation update

Jc2k (1):
      Add support for Homekit accessory battery sensors (#26210)

Jeff Irion (5):
      Load user-provided descriptions for python_scripts (#26069)
      Bump androidtv to 0.0.24 (#26158)
      Bump androidtv to 0.0.25 and add tests (#26202)
      Bump androidtv to 0.0.26 and update tests (#26340)
      Bump androidtv to 0.0.27 (#26497)

Johann Kellerman (3):
      DuckDNS setup backoff (#25899)
      SMA beta fix #26225 (#26244)
      Add person to device_sun_light_trigger (#25877)

John Luetke (1):
      Refactor pihole integration (#25837)

Jonathan Keljo (1):
      Add a keypress service for AlarmDecoder (#26100)

Josef Schlehofer (2):
      Upgrade youtube_dl to 2019.09.01 (#26330)
      Upgrade sqlalchemy to 1.3.8 (#26331)

Kevin McCormack (1):
      Add vivotek camera component (#26071)

Magnus Brange (1):
      Add protocol and model as an optional restriction for tellstick sensors (#26026)

Maikel Punie (4):
      Enable cert_expiry config entries  (#25624)
      Velbus config entries remove decorator (#26256)
      Enable SolarEdge config entries (#26282)
      Fix cert expiry config flow check and update (#26638)

Malte Franken (6):
      Fix WWLLN entity management (#26250)
      USGS Earthquakes icon for geolocation entities (#26353)
      GeoNet NZ Quakes Sensor (#26078)
      IGN Sismologia icon for geolocation entities (#26408)
      NSW Rural Fire Service icon for geolocation entities (#26416)
      Queensland Bushfire Alert icon for geolocation entities (#26439)

Marius (1):
      Change darksky icon for clear night (#26452)

Matt Schmitt (1):
      Bump dependency to add PLAY_STATE_STOPPED (#26239)

MatthewFlamm (1):
      Add NWS weather (#23647)

Matthias Alphart (1):
      Fix KNX light tunable white rounding error (#26364)

Oliver (1):
      Push to version 0.7.10 of denonavr (#26362)

On Freund (1):
      CoolMaster: Change auto to heat_cool (#26144)

Pascal Vizeli (45):
      Update azure-pipelines-release.yml for Azure Pipelines (#26128)
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Nightly builds (#26204)
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Enable py_noaa
      Update azure-pipelines-wheels.yml
      Update azure-pipelines-wheels.yml
      Add token support
      Update azure-pipelines-wheels.yml
      Update translations_upload
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update OpenCV 4.1.1 / Numpy 1.17.1 (#26387)
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Update azure-pipelines-translation.yml for Azure Pipelines
      Add prettier to vscode (#26417)
      Update azure-pipelines-translation.yml for Azure Pipelines
      Cleanup Dockerfile.dev (#26451)
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Update azure-pipelines-ci.yml for Azure Pipelines
      Nuki less strict (#26542)
      Ignore test output
      Improve startup of devcontainer (#26572)
      Cleanup stale script stuff (#26573)
      Bump UPC connect / fix auth issue (#26570)
      Deprecate Python 3.6.0 (#26575)
      Update azure-pipelines-release.yml
      Bumped version to 0.99.0b1
      Bump version to 0.99.0b2
      Fix Nuki issues (#26689)
      Bump connect-box library to fix logging (#26690)
      Fix release access for bram (#26693)

Paul Annekov (2):
      Fix tuya switch state (#26145)
      bump tuyaha 0.0.4 (#26303)

Paulus Schoutsen (32):
      Log warning if disabled entities receive updates. (#26143)
      Updated frontend to 20190822.0
      Reload config entry when entity enabled in entity registry, remove entity if disabled. (#26120)
      Allow bumping version for nightly builds (#26167)
      Updated frontend to 20190825.0
      Update translations
      Updated frontend to 20190828.0
      Add translations
      Fix partly cloudy (#26277)
      Remove deprecated SMA config (#26306)
      Add HEAD and PUT support to webhooks (#26299)
      Fix Alexa Report State (#26305)
      Fix alexa bad temp sensors (#26307)
      Expose current direction properly on state machine (#26298)
      Update translations
      Updated frontend to 20190901.0
      Allow passing dictionaries to async_register_entity_service (#26370)
      Allow passing None as input_text config (#26409)
      Fix state report (#26406)
      Allow core config updated (#26398)
      Do not complain about automatic generated files (#26540)
      Refactor Cast (#26550)
      Fix tests
      Home Assistant Cast (#26566)
      Updated frontend to 20190911.1
      Check if git is dirty before committing (#26588)
      Bumped version to 0.99.0b0
      Update PyChromecast (#26594)
      Use Nabu Casa url if no https url set (#26682)
      Verify withings config (#26698)
      Updated frontend to 20190918.1
      Bumped version to 0.99.0

Pawel (1):
      Fetch Onkyo current radio preset (#26211)

Penny Wood (1):
      Entity registry doesn't overwrite with None (#24275)

Phil Cole (1):
      Nissanleaf login fix (#26139)

Pierre (1):
      Add atome sensor platform (#26197)

Quentame (3):
      Add config flow to linky (#26076)
      Add device_info to Linky integration (#26477)
      Add Météo France icons + device_class (#26441)

Robert Svensson (10):
      deCONZ normalizes cover values to follow zigbee spec (#26240)
      UniFi - dont schedule updates on disabled entities (#26278)
      deCONZ - Dont update entry if data is equal
      UniFi - use entity registry disabled_by to control available entities  (#26141)
      Migrate Axis, deCONZ and UniFi to use config entry subclass (#26173)
      UniFi - Simplify getting controller from config entry (#26335)
      String has nothing to do with class method naming (#26368)
      deCONZ - use entity registry disabled_by to control available entities (#26219)
      deCONZ device automations (#26366)
      Remove support of UniFi device tracker configuration import (#26587)

Robert Van Gorkom (1):
      Add Withings support (#25154)

Rocik (1):
      Add support for Supla switches (#26188)

Santobert (1):
      Restructure Z-Wave Climate (#25724)

Sriram Vaidyanathan (1):
      Change xiaomi camera conf_host to template (#25799)

StephenWetzel (1):
      Add two new methods to the OpenUV component that consume only a singl… (#26207)

Steven Looman (1):
      Update to async_upnp_client==0.14.11 (#26515)

Steven Rollason (1):
      New template sensor attributes (#26127)

SukramJ (5):
      Add myself as codeowner to HmIP Cloud (#26140)
      Splitt device_state_attributes between device and group for Homematic IP Cloud (#26137)
      Fix for 0.98: Don't update disabled entities (Homematic IP Cloud) (#26236)
      Unify device_state_attributes handling for Homematic IP Cloud (#26449)
      Add Delta Counter of HmIP-SPDR to Homematic IP Cloud (#26538)

Sébastien RAMAGE (1):
      Update zigpy_zigate to 0.2.0 (#26327)

Taylor Silva (1):
      Add X10 devices as ISY994 switches (#26342)

ThaStealth (1):
      Remove solaredge_local duplicate code (#25941)

Tsvi Mostovicz (4):
      Jewish calendar binary sensor (#26200)
      Fix radiotherm local time (#26526)
      Make uk_transport sensor timezone/DST aware (#26577)
      Fix GTFS sensor wrong timezone (#26580)

Tyler Page (1):
      Venstar: define success for all branches of set_temperature() (#26148)

Ville Skyttä (3):
      Huawei LTE misc improvements (#26203)
      Test with 3.6.1 in Travis (#26347)
      Use PEP 526 type annotations, add some type hints (#26464)

croghostrider (1):
      Fix Emulated Hue AttributeError: 'NoneType' object has no attribute '… (#26018)

dieselrabbit (1):
      Update radiotherm climate attributes (#26465)

ehendrix23 (1):
      Update to 0.1.13 (#26402)

fmartens (1):
      Inverted rflink cover (#26038)

indykoning (1):
      Add growatt server integration (#25635)

jjlawren (4):
      Standardize Plex server connections (#26444)
      Add plex server config options to media_player platform (#26458)
      Move config and connections to Plex component (#26488)
      Remove default host for Plex config (#26583)

lifeisafractal (1):
      Add zwave application version (#26205)

mbo18 (1):
      Fix missing DarkSky mdi icon (#26274)

michaeldavie (1):
      Remove throttle from update (#26216)

newbee112 (1):
      Update sensor.py (#26218)

presslab-us (1):
      Support formatting and scaling with ZHA Metering cluster (#26201)

ruohan.chen (1):
      Support new climate arch for zhong_hong (#26309)

tyjtyj (2):
      Fix google_maps scan interval (#26328)
      Fix Tuya Light without brightness (#26534)

zewelor (4):
      Add device to mqtt camera (#26238)
      Add yeelight nightlight support via separate light entity (#26224)
      Add set scene service calls to yeelight (#26255)
      Fix yeelight inheritance order (#26706)