[update to 0.96.0] Fix AttributeError: 'NoneType' object has no attribute 'group' with sytadin component (#24652)
Aaron Bach (11):
      Add device class support for Ambient PWS sensors (#24677)
      Add RainMachine device classes where appropriate (#24682)
      Change Ambient solar radiation units to lx (#24690)
      Remove temperature attribute from SimpliSafe alarm control panel (#24833)
      Allow updating of via_device in device registry (#24921)
      Add support for Notion Home Monitoring (#24634)
      Add config flow support to Geolocation (#25046)
      Add support for World Wide Lightning Location Network (#25001)
      Change unique_id formula for Notion entities (#25076)
      Fix window exception in WWLLN (#25100)
      Fix missing sensor unit in RainMachine (#25101)

Adriaan Peeters (1):
      Add sonos.play_queue service (#24974)

Alain Tavan (1):
      fix an error in the description (#24735)

Alexei Chetroi (5):
      Bump ZHA dependencies. (#24637)
      Update ZHA dependencies. (#24736)
      Enhancement/zha model manuf (#24771)
      Bump up ZHA dependencies. (#25062)
      Fix climate is_aux_heat type hint. (#25170)

Anders Melchiorsen (10):
      Update LIFX brightness during long transitions (#24653)
      Fix time expression parsing (#24696)
      Update pysonos to 0.0.17 (#24740)
      Stability improvements for Sonos availability (#24880)
      Update pysonos to 0.0.19 (#24930)
      Add Sonos debug logging (#25063)
      Fix for Sonos debug logging (#25064)
      Support podcast episodes as Sonos favorites (#25087)
      Handle Sonos connection errors during setup (#25135)
      Update pysonos to 0.0.21 (#25168)

Andre Lengwenus (1):
      Corrected number of default LCN segment coupler scan tryouts (#24678)

Andre Richter (3):
      Add integration for Vallox Ventilation Units (#24660)
      Vallox: Fix missing hass member (#24753)
      Upgrade vallox to async client API (#24774)

Andrew Sayre (4):
      Bump pysmartthings (#24659)
      Move SmartThings imports to top (#24878)
      Improve SmartThings test mocking (#25028)
      Add hvac fan state (#25030)

Charles Garwood (1):
      Add websocket API command for Z-Wave network status (#25066)

Chris Johnston (1):
      Implement Twilio SMS notify MediaUrl support (#24971)

Chris Soyars (1):
      Add support for Yale YRL256 lock (#24932)

Conrad Juhl Andersen (1):
      Add support for sensor state STATE_UNAVAILABLE (#24641)

Daniel Høyer Iversen (5):
      Return correct name for met.no (#24763)
      Upgrade pytest to 5.0.0 (#24885)
      upgrade switchmate to latest lib (#25006)
      Sensibo, add HVAC_MODE_OFF (#25016)
      ambiclimate hvac_modes (#25015)

Daniel Perna (2):
      Update pyhomematic to 0.1.60 (#25152)
      Fix device types for some HomeMatic IP sensors (#25167)

Dave T (1):
      Add support for aurora ABB Powerone solar photovoltaic inverter (#24809)

David Bonnes (6):
      Tweak geniushub battery icons according to device state (#24798)
      [climate] Bugfix honeywell misleading error message (#25048)
      [climate] Add water_heater to evohome (#25035)
      [climate-1.0] Bugfix evohome showstopper (#25139)
      [climate-1.0] Add RoundThermostat to evohome (#25141)
      [climate] Tweak evohome migration (#25187)

David F. Mulcahey (10):
      ZHA fix device type mappings (#24699)
      Update ZHA dependencies (#24718)
      Remove device and entity registry entries when removing a ZHA device (#24369)
      Bump ZHA quirks module (#24802)
      Fix traceback during ZHA device removal (#24882)
      go back to signals and no hard entity references (#24894)
      Remove ZHA device entity (#24909)
      New scanner device tracker and ZHA device tracker support (#24584)
      bump zha-quirks version (#25059)
      Fix device name customization on ZHA add devices page (#25180)

David Winn (1):
      Sleepiq single sleeper crash (#24941)

Dennis Keitzel (1):
      Support mqtt discovery topic prefix with slashes (#24840)

Emilv2 (1):
      Remove obsolete comments in Dockerfile (#24748)

Evan Bruhn (1):
      Save cached logi_circle tokens in config folder (#24726)

Fabian Affolter (17):
      Upgrade discord.py to 1.2.2 (#24695)
      Upgrade youtube_dl to 2019.06.08 (#24692)
      Upgrade Sphinx to 2.1.2 (#24693)
      Upgrade luftdaten to 0.6.1 (#24842)
      Upgrade sqlalchemy to 1.3.5 (#24844)
      Upgrade numpy to 1.16.4 (#24845)
      Upgrade certifi to >= 2019.6.16 (#24846)
      Upgrade pyyaml to 5.1.1 (#24847)
      Upgrade jinja2 to >=2.10.1 (#24851)
      Upgrade psutil to 5.6.3 (#24854)
      Upgrade cryptography to 2.7 (#24852)
      Update praw to 6.3.1 (#23737)
      Upgrade youtube_dl to 2019.06.27 (#24875)
      Upgrade importlib-metadata to 0.18 (#24848)
      Upgrade bcrypt to 3.1.7 (#24850)
      Upgrade youtube_dl to 2019.07.02 (#24990)
      Upgrade luftdaten to 0.6.2 (#25177)

Franck Nijhof (6):
      Batch of Component(s) -> Integration(s) (#24972)
      Adds Lock Threads Probot (#24984)
      Adds Stale Probot for issues (#24985)
      Toon fixes for Climate 1.0 (#25027)
      Centralizes Toon data, reducing API calls (#23988)
      Improve toon climate (#25040)

Jeff Irion (3):
      Bump androidtv to 0.0.17 (#24886)
      Bump androidtv to 0.0.18 (#24927)
      Make sure volume level is valid when incrementing/decrementing (#25061)

Jesse Rizzo (1):
      Enphase envoy individual inverter production (#24445)

Joakim Plate (4):
      Correct socket use in cert_expiry platform (#25011)
      Add support for arcam fmj receivers (#24621)
      Support config flow on custom components (#24946)
      Load requirements for platforms (#25133)

Joakim Sørensen (2):
      Install requirements for integrations in packages before importing them. (#25005)
      Version sensor update (#25162)

Johann Kellerman (2):
      Add check_config helper (#24557)
      SMA catch error (#25045)

John Dyer (1):
      Update Waze route dependency to 0.10  (#24754)

John Luetke (1):
      Expose ports 8123, 8300 and 51827 in Dockerfile (#24389)

John Mihalic (1):
      Update pyHik library to 0.2.3 (#24957)

Jonathan (1):
      Add aml_thermal label (#24665)

Jonathan Keljo (1):
      Upgrade sisyphus-control to 2.2 (#24837)

Josh Anderson (3):
      Use climate device's target temp step value (#24804)
      Use step from tado rather than assuming 0.1 (#24807)
      Remove check and restore temp/mode changes (#25149)

Kevin Fronczak (1):
      Upgrade blinkpy==0.14.1 for startup bugfix (#24656)

Khole (2):
      [Climate] Hive Add water heater Component post the refresh of the climate component. (#25148)
      Hive water heater - Remove Duplication of appending entities (#25210)

Luuk (1):
      Add template vacuum support (#22904)

Maikel Punie (1):
      Velbus: autodiscover covers (#24877)

Malte Franken (1):
      updated geojson_client library to version 0.4 (#25039)

Markus Jankowski (2):
      Add climate related services to Homematic IP Cloud (#25079)
      remove comfort mode (#25140)

Martijn van Zal (1):
      Change phrases in the logbook component for persons and binary_sensors (#25053)

Martin Hjelmare (2):
      Fix device tracker see for entity registry entities (#24633)
      Fix locative device update (#24744)

Matte23 (2):
      Add support for IPP Printers to the CUPS integration (#24756)
      Added marker sensor to CUPS integration (#25037)

Niels Mündler (2):
      Fronius (solar energy and inverter) component (#22316)
      Fix monitoring of trays in syncthru component (#24961)

Oleg Kurapov (1):
      Extend websocket method usage to port 8002 in Samsung TV media player (#24716)

On Freund (1):
      Add turn on/off to coolmaster (#25097)

Pascal Vizeli (29):
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Prefere binary with wheels (#24669)
      Update azure-pipelines-release.yml for Azure Pipelines
      Add initial support for remote dev container (#24681)
      Update azure-pipelines-release.yml for Azure Pipelines (#24800)
      Full speed azure
      Update azure-pipelines-ci.yml for Azure Pipelines
      Update azure-pipelines-ci.yml for Azure Pipelines
      Update azure-pipelines-ci.yml for Azure Pipelines
      Update azure-pipelines-ci.yml for Azure Pipelines
      Update azure-pipelines-ci.yml for Azure Pipelines
      Add git editor / app port
      Update devcontainer.json
      Update devcontainer.json
      Update devcontainer.json
      Climate 1.0 (#23899)
      homematic add off support for climate (#25017)
      Update build pipeline
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines
      Support hass-release inside devcontainer (#25090)
      Add support for on/off climate (#25026)
      Fix powercontrol media player alexa (#25080)
      Version bump to 0.96.0b1
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Update azure-pipelines-wheels.yml for Azure Pipelines
      Update azure-pipelines-release.yml for Azure Pipelines

Paul Annekov (2):
      Switched from tuyapy to tuyaha as 1st one is not maintained (#24821)
      Update tuyaha to 0.0.2 to catch API exceptions (#25050)

Paulus Schoutsen (51):
      Warn when user tries run custom config flow (#24657)
      Clean up Google Config (#24663)
      Updated frontend to 20190620.0
      Update owner stream integration
      Updated frontend to 20190624.0
      Update translations
      AdGuard to update entry (#24737)
      Improve Alexa error handling (#24745)
      Updated frontend to 20190624.1
      Ignore duplicate tradfri discovery (#24759)
      Updated frontend to 20190626.0
      Entity to handle updates via events (#24733)
      Catch uncaught Alexa error (#24785)
      Make sure entity config is never none (#24801)
      Updated frontend to 20190627.0
      Add developer tools panel (#24812)
      Fix calling empty script turn off (#24827)
      Fix vacuum tests
      Make sure alert is set up after notify (#24829)
      Alexa sync state report (#24835)
      Guard for None entity config (#24838)
      Update translations
      Updated frontend to 20190630.0
      Updated frontend to 20190702.0
      Fix ecobee flaky test (#25019)
      Fix mimetypes on borked Windows machines (#25018)
      Fix Nest sensor (#25023)
      Updated frontend to 20190710.0
      Update translations
      Fix broken test in Python 3.7 (#25067)
      Correctly store removed entities for restore state (#25073)
      pylint
      Version bump to 0.96.0b0
      Do not reverse open/close calls (#24879)
      Guard module being None (#25077)
      Updated frontend to 20190712.0
      Bumped version to 0.96.0b2
      Updated frontend to 20190715.0
      Simplify Alexa/Google for new climate turn_on/off (#25115)
      Verify cloud user exists during boot (#25119)
      Allow area ID in service call schemas (#25121)
      Make dev tools titlte translatable (#25166)
      Bumped version to 0.96.0b3
      Bumped version to 0.96.0b4
      Updated frontend to 20190717.0
      Correctly set property decorator on preset modes (#25151)
      Only include target temp if has right support flag (#25193)
      Bumped version to 0.96.0
      Pin Docker to Debain Stretch (#25206)
      Fix ecobee missing preset mode support flag (#25211)
      Updated frontend to 20190717.1

Penny Wood (4):
      Template: Expand method to expand groups, and closest as filter (#23691)
      Update IDs for rename node/value (#24646)
      Changes as per code review of #24646 (#24917)
      Avoid flooding steam API (#23941)

Phil Bruckner (12):
      Add show_as_state options to Life360 (#24725)
      Fix life360 exception when no location provided (#24777)
      Fix another Life360 bug (#24805)
      Add template support to template trigger's for option (#24810)
      Bump life360 package to 4.0.1 (#24905)
      Fix 'same state' monitoring in numeric_state trigger (#24910)
      Fix 'same state' monitoring in state trigger (#24904)
      Add missing trigger.for variable to template trigger (#24893)
      Add datetime option to input_datetime.set_datetime service (#24975)
      Add template support to numeric_state trigger's for option (#24955)
      Add template support to state trigger's for option (#24912)
      Restore automation last_triggered as datetime & fix test (#24951)

Robert Dunmire III (1):
      Fix errors if rest source becomes unavailable (#24986)

Robin Wohlers-Reichel (2):
      Solax update 0.1.0 (#24708)
      Add 'unique_id' Property to Inverter Sensors (#24707)

Rodrigo Pérez (1):
      Vlc telnet (#24290)

Seweryn Zeman (1):
      Added missing yeelight models mapping (#24963)

Steven Looman (1):
      Upgrade to async_upnp_client==0.14.10 and increase search timeout (#24685)

Steven Rollason (1):
      Fix exclusion of routes with excl_filter (#24928)

Tejpal Sahota (1):
      Changed default encoding to mp3 (#24808)

Thomas Lovén (1):
      Allow extra js modules to be included in frontend (#24675)

Tom Harris (1):
      Upgrade insteonplm to 0.16.0 and add INSTEON scene triggering (#24765)

Tsvi Mostovicz (1):
      Upgrade hdate==0.8.8 (#25008)

Ville Skyttä (5):
      braviatv, nmap_tracker: use getmac for getting MAC addresses (#24628)
      Upgrade mypy to 0.710 (#24666)
      Upgrade pytest to 4.6.3 (#24782)
      Upgrade mypy to 0.711, drop no longer needed workarounds (#24998)
      Test dependency updates (#25004)

William Scanlon (1):
      Pubnub to 1.0.8 (#24781)

William Sutton (1):
      Add radiotherm CT80 current humidity support (#25024)

arigilder (1):
      Add missing support for jewish_calendar.omer_count sensor (#24958)

cdce8p (1):
      Remove myself as codeowner (#25043)

cgtobi (10):
      Bump version pyatmo to 2.0.1 (#24703)
      Bump pyatmo to v2.1.0 (#24724)
      Handle timeouts gracefully (#24752)
      Fix netatmo weatherstation setup error  (#24788)
      Fix home coach discovery (#24902)
      Implement ADR0003 for Netatmo sensor (#24944)
      Fix Netatmo climate presets (#25029)
      Fix Netatmo rain gauge precision (#25036)
      Fix Netatmo climate issue when device out of reach (#25096)
      Fix schema validation for service calls (#25204)

dreed47 (1):
      Zestimate fix for issue #23837 (#23838)

endor (1):
      Add Trafikverket train component (#23470)

foreign-sub (1):
      Fix AttributeError: 'NoneType' object has no attribute 'group' with sytadin component (#24652)

h3ndrik (1):
      Add time delta option when searching for deutsche_bahn connections (#24600)

jlrgraham (1):
      Bump pyvera to 0.3.2, null/missing value protection (#25041)

kevank (1):
      Update tts.py (#24892)

kreegahbundolo (1):
      Add ability to send attachments in pushover notifications (#24806)

ktnrg45 (1):
      Fix PS4 entities with shared host not updating and latency with multiple connections (#24642)

monte-monte (1):
      Complete OPERATION_MODES (#25069)

mvn23 (1):
      Multiple devices support for opentherm_gw (#22932)

realthk (1):
      Hungarian is also supported in Google Cloud TTS  (#24861)

sfjes (1):
      Fix downloader_download_failed event not firing for HTTP response errors (#24640)

zewelor (3):
      Improve autodiscovered yeelights model detection (#24671)
      Fix yeelight color temp getter (#24830)
      Fix mysensors icon name (#24871)

Дубовик Максим (1):
      New languages that looks like supported by Google but not documented: (#24881)